### ISSUE TITLE
Issue with YAML

### ISSUE THREAD

**Issue by tractionwise** [ovh/website-evidence-collector-batch#14]
Hi guys,
First of all big thanks to this great tool adaption. I already saw from an acquaintance how results might look like. 
I am currently not getting the batch-version to run as i run into this error. How can I solve this issue? I am not a deep tech developer and thus not directly seeing where might be the issue. I already checked the loader.js file with nano-editor on Mac, but can't see a problem there. Thanks in advance. 

`[ERROR][DEVELOPMENT] YAMLException: missed comma between flow collection entries at line 2, column 34:
    \cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 He ... 
                                     ^
    at generateError (/Users/andrew/.npm-packages/lib/node_modules/website-evidence-collector-batch/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/Users/andrew/.npm-packages/lib/node_modules/website-evidence-collector-batch/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at readFlowCollection (/Users/andrew/.npm-packages/lib/node_modules/website-evidence-collector-batch/node_modules/js-yaml/lib/js-yaml/loader.js:718:7)
    at composeNode (/Users/andrew/.npm-packages/lib/node_modules/website-evidence-collector-batch/node_modules/js-yaml/lib/js-yaml/loader.js:1360:11)
    at readBlockMapping (/Users/andrew/.npm-packages/lib/node_modules/website-evidence-collector-batch/node_modules/js-yaml/lib/js-yaml/loader.js:1036:16)
    at composeNode (/Users/andrew/.npm-packages/lib/node_modules/website-evidence-collector-batch/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readDocument (/Users/andrew/.npm-packages/lib/node_modules/website-evidence-collector-batch/node_modules/js-yaml/lib/js-yaml/loader.js:1525:3)
    at loadDocuments (/Users/andrew/.npm-packages/lib/node_modules/website-evidence-collector-batch/node_modules/js-yaml/lib/js-yaml/loader.js:1588:5)
    at load (/Users/andrew/.npm-packages/lib/node_modules/website-evidence-collector-batch/node_modules/js-yaml/lib/js-yaml/loader.js:1614:19)
    at Object.safeLoad (/Users/andrew/.npm-packages/lib/node_modules/website-evidence-collector-batch/node_modules/js-yaml/lib/js-yaml/loader.js:1637:10)
    at readFile (/Users/andrew/.npm-packages/lib/node_modules/website-evidence-collector-batch/src/lib/files.js:21:22)
    at async Config.load (/Users/andrew/.npm-packages/lib/node_modules/website-evidence-collector-batch/src/lib/config.js:14:26)
    at async getConfig (/Users/andrew/.npm-packages/lib/node_modules/website-evidence-collector-batch/bin/cli.js:14:5)
    at async /Users/andrew/.npm-packages/lib/node_modules/website-evidence-collector-batch/bin/cli.js:31:20
`

**Comment by tractionwise** [comment]
I found the mistake myself. I had some formatting bugs in the config.yaml which caused this problem. I checked it with this tool [YAML-Validator](https://jsonformatter.org/yaml-validator), in case anyone also comes across a similar bug.
